name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Upload
        run: make all
        env:
          HELM_REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
         