name: Release Charts

on:
  push:
    branches:
      - main
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: package check local
        if: ${{ github.ref == 'refs/heads/main' }}
        run: make local

      - name: Upload
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: make all
        env:
          HELM_REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
         